#!/usr/bin/env bash
# tools/bank-to-ogg.sh — convert FMOD `.bank` archives to a Ruleste audio pack.
#
# Pipeline:  vgmstream-cli decodes every subsong in each `.bank` to a WAV
# named after its FMOD stream name, then ffmpeg encodes each WAV to Ogg Vorbis.
# A companion `audio.manifest` is emitted so the engine can look up samples.
#
# Why vgmstream, not a hand-rolled parser:
#   Celeste's banks wrap FSB5 "Custom Vorbis" samples inside an FMOD Studio
#   RIFF/FEV container; decoding requires FMOD's embedded Vorbis setup tables.
#   vgmstream already understands all of that; re-implementing it in Rust would
#   pull in megabytes of vendor codebook data and violate the "don't depend on
#   references / stay framework-free" spirit (this is a *dev* conversion tool,
#   not an engine dependency).
#
# Usage:
#   tools/bank-to-ogg.sh <bank-dir> <out-dir>      # convert
#   tools/bank-to-ogg.sh --self-test               # quick wired-up check
#
# Nix (preferred):  nix shell nixpkgs#vgmstream nixpkgs#ffmpeg -c \
#                     tools/bank-to-ogg.sh <bank-dir> <out-dir>
#
# Output layout:
#   <out-dir>/
#     <bank_stem>/
#       <stream_name>.ogg          # one per subsong in the bank
#       audio.manifest             # "<stream_name>\tbank=<stem>\tfile=<bank_stem>/<stream_name>.ogg"
#     audio.manifest               # top-level merge referencing each bank
set -euo pipefail

if [[ "${1:-}" == "--self-test" ]]; then
    need=(vgmstream-cli ffmpeg)
    for c in "${need[@]}"; do
        if ! command -v "$c" >/dev/null 2>&1; then
            echo "self-test: missing '$c'." >&2
            echo "run via:  nix shell nixpkgs#vgmstream nixpkgs#ffmpeg -c tools/bank-to-ogg.sh --self-test" >&2
            exit 1
        fi
    done
    echo "self-test OK: vgmstream-cli=$(command -v vgmstream-cli) ffmpeg=$(command -v ffmpeg)"
    exit 0
fi

if [[ $# -lt 2 ]]; then
    echo "usage: $0 <bank-dir> <out-dir>" >&2
    exit 2
fi

bank_dir=$1
out_dir=$2

if [[ ! -d "$bank_dir" ]]; then
    echo "error: bank dir '$bank_dir' not found" >&2
    exit 1
fi
mkdir -p "$out_dir"

top_manifest="$out_dir/manifest"
: >"$top_manifest"
{
    echo "# Ruleste audio manifest — generated by tools/bank-to-ogg.sh"
    echo "# Format: 'sample_name'  'bank'  'file'"
    echo "# Sample names are the FSB5 stream names (lowercased), which are the"
    echo "# primary audio key. FMOD event:/... -> stream-name remapping is"
    echo "# deferred to a ROADMAP research item (strings.bank is a private format)."
} >>"$top_manifest"

shopt -s nullglob
banks=( "$bank_dir"/*.bank )
# Skip *.strings.bank (they carry event-name metadata, not audio samples).
audio_banks=()
for b in "${banks[@]}"; do
    case "$b" in
        *".strings.bank") ;;
        *) audio_banks+=( "$b" ) ;;
    esac
done

if [[ ${#audio_banks[@]} -eq 0 ]]; then
    echo "error: no audio '.bank' files in '$bank_dir' (only .strings.bank found)" >&2
    exit 1
fi

for bank in "${audio_banks[@]}"; do
    stem=$(basename "$bank" .bank)
    # FMOD names like "Master Bank", trailing spaces — normalise to a path-safe stem.
    safe_stem=${stem// /_}
    bank_out="$out_dir/$safe_stem"
    mkdir -p "$bank_out"

    # 1) Decode every subsong; vgmstream's '?n' is the FMOD stream name.
    echo "==> decoding $bank -> $bank_out"
    # wavtemp/{streamname}.wav
    wav_tmp="$bank_out/.wavtmp"
    mkdir -p "$wav_tmp"
    vgmstream-cli -i -S 0 -o "$wav_tmp/?n.wav" "$bank" >/dev/null 2>&1 || {
        # vgmstream uses non-zero exit on truncated streams; keep going
        echo "  warning: vgmstream reported issues for $bank (continuing)" >&2
    }

    # 2) Encode each WAV to OGG Vorbis (VBR q4) and build the per-bank manifest.
    per_manifest="$bank_out/manifest"
    : >"$per_manifest"
    printf '# bank=%s\n' "$stem" >>"$per_manifest"

    shopt -s nullglob
    wavs=( "$wav_tmp"/*.wav )
    [[ ${#wavs[@]} -eq 0 ]] && { echo "  error: no subsongs decoded from $bank" >&2; exit 1; }
    for w in "${wavs[@]}"; do
        name=$(basename "$w" .wav)
        ogg="$bank_out/$name.ogg"
        ffmpeg -nostdin -hide_banner -loglevel error -y -i "$w" -c:a libvorbis -q:a 4 "$ogg"
        printf '%s\t%s\t%s\n' "$name" "$stem" "$safe_stem/$name.ogg" >>"$per_manifest"
    done
    rm -rf "$wav_tmp"

    printf '%s\t%s\t%s\n' "${stem}" "(bank)" "$safe_stem/" >>"$top_manifest"
    echo "    -> $(ls "$bank_out"/*.ogg | wc -l) OGG files + manifest"
done

echo "Done."
echo "Manifest: $top_manifest"
echo "Next: remap event:/... paths onto sample names (parse strings.bank)."
